// automatically generated by the FlatBuffers compiler, do not modify

package dto.user

@Suppress("unused")
@ExperimentalUnsignedTypes
class Gender private constructor() {
    companion object {
        const val Male: Byte = 0
        const val Female: Byte = 1
        val names : Array<String> = arrayOf("Male", "Female")
        fun name(e: Int) : String = names[e]
    }
}
